# Generated by Django 5.2.8 on 2025-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0008_merge_20251223_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='notizia',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', max_length=200, unique=True),
        ),
    ]
