# Generated by Django 5.2.8 on 2025-12-31 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0010_auto_slug_all_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='eventi/gallery/')),
                ('didascalia', models.CharField(blank=True, max_length=200, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='parco_verismo.evento')),
            ],
            options={
                'verbose_name': 'Immagine Evento',
                'verbose_name_plural': 'Immagini Evento',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='NotiziaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='notizie/gallery/')),
                ('didascalia', models.CharField(blank=True, max_length=200, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('notizia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='parco_verismo.notizia')),
            ],
            options={
                'verbose_name': 'Immagine Notizia',
                'verbose_name_plural': 'Immagini Notizia',
                'ordering': ['ordine'],
            },
        ),
    ]
