# Generated by Django 5.2.8 on 2025-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0012_alter_itinerario_options_alter_opera_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('luogo', models.CharField(choices=[('vizzini', 'Vizzini'), ('mineo', 'Mineo'), ('licodia', 'Licodia Eubea')], max_length=20, verbose_name='Luogo')),
                ('itinerario', models.CharField(choices=[('verghiani', 'Itinerari verghiani'), ('capuaniani', 'Itinerari capuaniani'), ('tematici', 'Itinerari tematici')], max_length=20, verbose_name='Tipologia itinerario')),
                ('data_richiesta', models.DateTimeField(auto_now_add=True, verbose_name='Data richiesta')),
                ('evasa', models.BooleanField(default=False, verbose_name='Evasa')),
                ('note_admin', models.TextField(blank=True, help_text='Note interne per il follow-up', verbose_name='Note amministratore')),
            ],
            options={
                'verbose_name': 'Richiesta di Contatto',
                'verbose_name_plural': 'Richieste di Contatto',
                'ordering': ['-data_richiesta'],
            },
        ),
    ]
