# Generated by Django 5.2.8 on 2025-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0013_richiestacontatto'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestacontatto',
            name='data_evasione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data evasione'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='data_preferita',
            field=models.DateField(blank=True, help_text='Opzionale', null=True, verbose_name='Data preferita visita'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='messaggio',
            field=models.TextField(blank=True, help_text='Eventuali richieste o informazioni aggiuntive', verbose_name='Messaggio/Richieste particolari'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='numero_partecipanti',
            field=models.PositiveIntegerField(default=1, help_text='Numero persone che parteciperanno', verbose_name='Numero partecipanti'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='priorita',
            field=models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Priorità'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='responsabile',
            field=models.CharField(blank=True, help_text='Chi ha gestito la richiesta', max_length=100, verbose_name='Responsabile'),
        ),
        migrations.AddField(
            model_name='richiestacontatto',
            name='telefono',
            field=models.CharField(blank=True, help_text='Opzionale ma consigliato per contatto rapido', max_length=20, verbose_name='Telefono'),
        ),
    ]
