# Generated by Django 5.2.8 on 2025-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0014_richiestacontatto_data_evasione_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RichiestaContatto',
            new_name='Prenotazione',
        ),
    ]
