# Generated by Django 5.2.8 on 2025-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0015_rename_richiesta_to_prenotazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'ordering': ['-data_richiesta'], 'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='comunicazioni',
            field=models.TextField(blank=True, help_text='Storico email/telefonate', verbose_name='Log comunicazioni'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='costo_effettivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo effettivo €'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='costo_preventivato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo preventivato €'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='data_completamento',
            field=models.DateTimeField(blank=True, help_text='Quando il servizio è stato erogato', null=True, verbose_name='Data completamento'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='data_conferma',
            field=models.DateTimeField(blank=True, help_text='Quando la prenotazione è stata confermata', null=True, verbose_name='Data conferma'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='esito',
            field=models.CharField(blank=True, choices=[('', 'Non ancora definito'), ('eccellente', 'Eccellente'), ('buono', 'Buono'), ('sufficiente', 'Sufficiente'), ('problematico', 'Problematico')], max_length=20, verbose_name='Esito visita'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='feedback_cliente',
            field=models.TextField(blank=True, verbose_name='Feedback cliente'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='guida_assegnata',
            field=models.CharField(blank=True, help_text='Nome della guida turistica assegnata', max_length=100, verbose_name='Guida assegnata'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='modificato_da',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modificato da'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='note_pubbliche',
            field=models.TextField(blank=True, help_text='Informazioni da comunicare al cliente', verbose_name='Note per il cliente'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='pagamento_ricevuto',
            field=models.BooleanField(default=False, verbose_name='Pagamento ricevuto'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='rating_cliente',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Feedback del cliente', null=True, verbose_name='Valutazione cliente (1-5)'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('nuova', 'Nuova richiesta'), ('in_lavorazione', 'In lavorazione'), ('confermata', 'Confermata'), ('completata', 'Completata'), ('cancellata', 'Cancellata'), ('no_show', 'Non presentato')], db_index=True, default='nuova', max_length=20, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='tipo_pagamento',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('contanti', 'Contanti'), ('bonifico', 'Bonifico'), ('carta', 'Carta'), ('altro', 'Altro')], default='gratuito', max_length=20, verbose_name='Tipo pagamento'),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='ultima_modifica',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modifica'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='data_evasione',
            field=models.DateTimeField(blank=True, help_text='Deprecato: usa data_completamento', null=True, verbose_name='Data evasione'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='evasa',
            field=models.BooleanField(default=False, help_text="Deprecato: usa campo 'stato'", verbose_name='Evasa'),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='priorita',
            field=models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta')], db_index=True, default='media', max_length=10, verbose_name='Priorità'),
        ),
    ]
