# Generated by Django 5.2.8 on 2025-12-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0016_alter_prenotazione_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='comunicazioni',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='costo_effettivo',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='costo_preventivato',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='data_conferma',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='esito',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='feedback_cliente',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='modificato_da',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='note_pubbliche',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='pagamento_ricevuto',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='rating_cliente',
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='tipo_pagamento',
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('nuova', 'Nuova richiesta'), ('in_lavorazione', 'In lavorazione'), ('confermata', 'Confermata'), ('completata', 'Completata'), ('cancellata', 'Cancellata')], db_index=True, default='nuova', max_length=20, verbose_name='Stato'),
        ),
    ]
